### ISSUE TITLE
Create "one match" component

### ISSUE THREAD

**Issue by RobbertWolfs** [nerd-labs/mutambo#17]
thuis - uit ploeg
score

**Comment by RobbertWolfs** [comment]
Naam Ploeg 1 - Score - Naam Ploeg 2

![Screen Shot 2018-03-07 at 08.53.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56209ceedebe572000244570/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f46b7191a378e70c2e52415f46be5d4a1f06a3a3dc78e2a436628f0d08efd33e097cc26f47aabd821fbf03bc23894ed4b5b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca58f24be84c5cad143167f43b.png)

**Comment by WartClaes** [comment]
add "start match" button -> all other matches of the 2 players will be "locked"

**Comment by WartClaes** [comment]
https://codepen.io/WartClaes/pen/EEPMWY?editors=1100
