### ISSUE TITLE
(knockout) match error (aka tie) design

### ISSUE THREAD

**Issue by RobbertWolfs** [nerd-labs/mutambo#170]

**Comment by WartClaes** [comment]
![Screen Shot 2018-06-20 at 09.45.32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563b04d2badddd3f00682f68/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f36b7191a378e60c2f54415c4cbe5d4a1f06a3a3dc78e2a436628f0d08efd33e097cc26f47aabd821fbf03bc23894ed4b5b99850d2aa6c7bb3d4d216744b470a83ed5f34aa984eca51f243e14a51a1133e67f43b.png)
