### ISSUE TITLE
scoped styling does not work properly

### ISSUE THREAD

**Issue by WartClaes** [nerd-labs/mutambo#27]
![Screen Shot 2018-03-05 at 19.03.39.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/563b04d2badddd3f00682f68/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379e60c2b52415c47be5d4a1f06a3a3dc78e2a436628f0d08efd33e097cc26f47aabd821fbf03bc23894ed4b5b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca58f44ce24c56a3153665f43b.png)

**Comment by RobbertWolfs** [comment]
Welke branch? Dan kijk ik even

**Comment by WartClaes** [comment]
feature/issue-#24-add-logo-component

**Comment by RobbertWolfs** [comment]
met css lijkt het te werken
